services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: shift-planner-db
    environment:
      POSTGRES_DB: shift_planner
      POSTGRES_USER: shift_user
      POSTGRES_PASSWORD: shift_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - shift-planner-network
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shift-planner-backend
    environment:
      - DATABASE_URL=postgresql://shift_user:shift_password@postgres:5432/shift_planner
      - SECRET_KEY=your-super-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=["http://localhost:3000","http://frontend:3000"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - shift-planner-network
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/__pycache__

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shift-planner-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - shift-planner-network
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
    driver: local

networks:
  shift-planner-network:
    driver: bridge 